version: '3'

services:
  mysql:
    container_name: mysql_dm
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "app"
    ports:
      - "3307:3306"

  fastapi_app:
    container_name: fastapi_dm
    build: ./app
    depends_on:
      - mysql
    # environment:
    #   DATABASE_URL: mysql+pymysql://root:root@mysql:3306/app
    ports:
      - "8000:8000"

networks:
  solution:
    driver: bridge